package com.umlcc.model;

public enum Warning {
    NONE,
    NO_JAVADOC,
    NO_JAVADOC_CLASS,
    NO_JAVADOC_METHOD,
    NO_JAVADOC_PARAMETER,
    NO_JAVADOC_RETURN,
    NO_JAVADOC_AUTHOR,
    INCORRECT_PRIVACY_ATTRIBUTE,
    INCORRECT_PRIVACY_METHOD,
    NOT_FOLLOWING_UML,
    EXTRA_CLASS_ATTRIBUTE,
    EXTRA_NON_PRIVATE_METHOD,
    MISSING_FILE,
    EXTRA_FILE,
    INDENTATION_ISSUES,
    SPACING_ISSUES,
}